apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ingressgateway
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: istio-ingressgateway
    env: dev
    app.kubernetes.io/part-of: cloudops
    app.kubernetes.io/managed-by: argocd
spec:
  namespaceSelector:
    matchNames:
      - istio-ingress
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 30s
