{{- if .Values.releaseRecords.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.releaseRecords.postgres.serviceName }}
  namespace: {{ .Values.base.namespace }}
  labels:
{{ include "cloudops-go.labels" . | indent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.releaseRecords.postgres.serviceName }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
