base:
  envName: dev
  namespace: cloudops-dev

app:
  serviceName: cloudops-gateway
  servicePort: 80
  ingressPath: /api
  imageTag: main-8
  replicas: 2

service:
  targetPort: 8080
  type: ClusterIP

argocd:
  enabled: false
  server: https://argocd.jianggan.cn
  insecure: "true"
  tokenSecret:
    name: cloudops-cicd-argocd-token
    key: token
