apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-backend
  namespace: argocd
spec:
  description: CloudOps dev backend applications
  sourceRepos:
    - https://github.com/jianggan20240209/cloudops-gitops.git
  destinations:
    - namespace: cloudops-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
