apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: tracing
  labels:
    app.kubernetes.io/name: tempo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
