apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway-monitor-dev
  namespace: argocd
spec:
  project: dev-platform
  source:
    repoURL: https://github.com/jianggan20240209/cloudops-gitops.git
    targetRevision: main
    path: dev/platform/istio/ingress-gateway-monitor
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
