apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-gateway-rollout-dev
  namespace: argocd
spec:
  project: dev-backend
  source:
    repoURL: https://github.com/jianggan20240209/cloudops-gitops.git
    targetRevision: main
    path: dev/backend/rollouts/chart
    helm:
      valueFiles:
        - values/cloudops-gateway.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudops-dev
  ignoreDifferences:
    - group: networking.istio.io
      kind: VirtualService
      name: cloudops-gateway-rollout
      namespace: cloudops-dev
      jqPathExpressions:
        - .spec.http[].route[].weight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
